// Generates src/styles/tokens.css from design/tokens.json.
// Runs on `predev` and `prebuild`. Do not edit tokens.css by hand.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'design/tokens.json'), 'utf8'));

/** Resolve a token value for one theme; `{alias}` becomes var(--alias). */
function themed(value, theme) {
  const raw = typeof value === 'string' ? value : value[theme] ?? value.dark;
  return raw.replace(/\{([a-z0-9-]+)\}/gi, 'var(--$1)');
}

function themeBlock(theme) {
  const lines = [];
  for (const t of tokens.color.tokens) lines.push(`  --${t.name}: ${themed(t.value, theme)};`);
  for (const t of tokens.shadow.tokens) lines.push(`  --${t.name}: ${themed(t.value, theme)};`);
  lines.push(`  color-scheme: ${theme};`);
  return lines.join('\n');
}

const spacing = [...tokens.spacing.tokens];
if (!spacing.some((t) => t.name === 'space-30')) spacing.push({ name: 'space-30', value: '120px' });

const staticLines = [
  ...spacing.map((t) => `  --${t.name}: ${t.value};`),
  ...tokens.radius.tokens.map((t) => `  --${t.name}: ${t.value};`),
  ...Object.entries(tokens.type.families).map(([k, v]) => `  --font-${k}: ${v};`),
  '  /* Native Nights band only (its own brand colours). */',
  '  --nn-plum: #7E305A;',
  '  --nn-lavender: #DBD1EB;',
];

const typeLines = [];
const classLines = [];
for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    const family = s.family ?? group.family;
    typeLines.push(`  --fs-${s.name}: ${s.fontSize};`, `  --lh-${s.name}: ${s.lineHeight};`);
    const decl = [
      `font-family: var(--font-${family});`,
      `font-size: var(--fs-${s.name});`,
      `line-height: var(--lh-${s.name});`,
      `font-weight: ${s.fontWeight};`,
      `letter-spacing: ${s.letterSpacing ?? 'normal'};`,
    ];
    if (s.name === 'label') decl.push('text-transform: uppercase;');
    classLines.push(`.t-${s.name} { ${decl.join(' ')} }`);
  }
}

const fontFaces = tokens.type.fonts.map(
  (f) => `@font-face {
  font-family: '${f.family}';
  src: url('/${f.file}') format('woff2-variations'), url('/${f.file}') format('woff2');
  font-weight: ${f.weight};
  font-style: normal;
  font-display: swap;
}`,
);

const css = `/* GENERATED by scripts/build-tokens.mjs from design/tokens.json. Do not edit. */

${fontFaces.join('\n\n')}

:root {
${staticLines.join('\n')}
${typeLines.join('\n')}
}

/* Dark is the primary theme. .theme-dark re-applies it inside a light section. */
:root,
.theme-dark {
${themeBlock('dark')}
}

.theme-light {
${themeBlock('light')}
}

${classLines.join('\n')}
`;

writeFileSync(resolve(root, 'src/styles/tokens.css'), css);
console.log('tokens.css written');
